### ISSUE TITLE
Server name

### ISSUE THREAD

**Issue by angelsanchez** [konstellation-io/kdl-server#31]
- [ ] Create a helm value called `serverName`
- [ ] admin-ui will serve a static JSON file at `<base_url>/config.json` with the `serverName` value:
```
{
  ...
  "SERVER_NAME": "<serverName>"
}
```
To achieve this use a config-map like:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-ui-configmap
  labels:
    {{- include "kdl.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-admin-ui
data:
  config.json: |
    {
      "SERVER_NAME": "{{ .Values.serverName }}"
    }
```
- [ ] To add a new server, the electron app will use this `<base_url>/config.json` to check that the URL is valid and to get the server name
- [ ] the admin-ui will load this config.json on page loading
