### ISSUE TITLE
Ingresses config should not be global

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#618]
Right now the ingress configuration is being attached using a single global configuration that is set in the `values.yml` file.

values.yml
```yaml
ingress:
  type: nginx
  nginxConnectionTimeout: "3600"
```

The problem is that the `ingress.timeout` parameter is only being passed to `templates/app/ingress.yaml` file while `ingress.type` parameter is being passed to the rest of the ingress.yaml template files in the chart. Moreover, the `ingress.timeout` is being used to set different annotations in the `templates/app/ingress.yaml` manifest template, which could be a problem.

templates/app/ingress.yaml
```yaml
metadata:
  name: kdl-server
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000000m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.nginxConnectionTimeout }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.nginxConnectionTimeout }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.nginxConnectionTimeout }}"
    {{ end }}
spec:
```

The solution could be to annidate an `ingress` object inside all the main components of the chart inside the `values.yml` file allowing annotations to be set freely.:
values.yml 
```
kdlServer:
  ingress:
    type: nginx
    annotations: {}
    
gitea:
  ingress:
    type: nginx
    annotations: {}
```
 And so on.
