### ISSUE TITLE
Usertools operator gitea-oauth2-setup image tag is set to "latest"

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#620]
On chart release v0.13.2 the default value for `userToolsOperator.giteaOauth2Setup.image.tag` is set to **latest** when it should be set to **v0.13.2**.

Check values.yml:

```
...
userToolsOperator:
  image:
    repository: konstellation/user-tools-operator
    tag: v0.13.2
    pullPolicy: IfNotPresent
  storage:
    size: 10Gi
    storageClassName: standard
  jupyter:
    image:
      repository: konstellation/jupyter-gpu
      tag: v0.13.2
      pullPolicy: IfNotPresent
  repoCloner:
    image:
      repository: konstellation/repo-cloner
      tag: v0.13.2
      pullPolicy: IfNotPresent
  vscode:
    image:
      repository: konstellation/vscode
      tag: v0.13.2
      pullPolicy: IfNotPresent
  giteaOauth2Setup:
    image:
      repository: konstellation/gitea-oauth2-setup
      tag: "latest"
      pullPolicy: IfNotPresent
  oauth2Proxy:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.0.1-amd64
      pullPolicy: IfNotPresent
...
```
