### ISSUE TITLE
Project operator mlflow image tag is set to "latest"

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#623]
On chart release v0.13.2 the default value for projectOperator.mlflow.image.tag is set to latest when it should be set to v0.13.2.

Check values.yml:

```yaml
projectOperator:
  image:
    repository: konstellation/project-operator
    tag: v0.13.2
    pullPolicy: IfNotPresent
  mlflow:
    image:
      repository: konstellation/mlflow
      tag: latest
      pullPolicy: IfNotPresent
    volume:
      storageClassName: standard
      size: 1Gi
  filebrowser:
    image:
      repository: filebrowser/filebrowser
      tag: v2
      pullPolicy: IfNotPresent
```
