### ISSUE TITLE
Backup image tag is set to "latest"

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#624]
On chart release v0.13.2 the default value for backup.image.tag is set to latest when it should be set to v0.13.2.

Check values.yml:
```yaml
backup:
  name: backup-gitea
  image:
    repository: konstellation/kdl-backup
    tag: latest
    pullPolicy: IfNotPresent
```
