### ISSUE TITLE
Allow Project Operator deployment resources specification

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#637]
Currently there is not a way to specify resource **limits** and **requests** configuration via `values.yml` in the main container (manager).

Check `helm/kdl-server/templates/project-operator/deployment.yaml` file:
```yaml
     - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --leader-election-id=project-operator
        image: {{ .Values.projectOperator.image.repository }}:{{ .Values.projectOperator.image.tag }}
        imagePullPolicy: {{ .Values.projectOperator.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 60Mi
        securityContext:
          allowPrivilegeEscalation: false
```
