### ISSUE TITLE
Pass user-tools tls secret name from values.yaml

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#799]
Currently the created *user-tools* are assuming that a TLS secret with the following name exists: `{{ .Values.domain }}-tls-secret`.

```
spec:
  {{ if .Values.tls.enabled -}}
  tls:
    - hosts:
        - {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
        - {{ .Values.usernameSlug }}-jupyter.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
```
This is problematic because if the chart user decides to use a different secret which name doesn't fit the above template, the user-tools ingress will serve a kubernetes self-signed certificate.

Complements #801 and #802
