### ISSUE TITLE
Allow pass ingress annotations from values.yaml

### ISSUE THREAD

**Issue by alpiquero** [konstellation-io/kdl-server#804]
Currently there is no way for users to specify ingress annotations because they are being generated from inside the chart.

See `helm/kdl-server/templates/gitea/ingress.yaml`

```
...
kind: Ingress
metadata:
  name: gitea
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: ALLOW-FROM {{ include "protocol" . }}://kdlapp.{{ .Values.domain }}";
      more_set_headers "Content-Security-Policy: frame-ancestors 'self' {{ include "protocol" . }}://kdlapp.{{ .Values.domain}}";
    {{ end }}
...
```

It is necessary to pass them as follows from `values.yaml` on some way. For example:

```
kdlServer:
  ingress:
     annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-body-size: "1000000m"
```

On that way users could add extra annotations for additional ingress config such as cert-manager config.
