### ISSUE TITLE
Update Project Tools schema

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kdl-server#84]
Replace the `tools` Project field with `toolUrls`:
```
type Project {
-  tools: [Tool!]!
+ toolUrls: ToolUrls!
}
```

This object will contain all URLs for each project tool:
```
type ToolUrls {
  gitea: String!
  minio: String!
  jupyter: String!
  vscode: String!
  drone: String!
  mlflow: String!
}
```

In the API, these URLs will come from env vars set in the deployment: `helm/kdl-server/templates/app/deployment.yaml`

```
      containers:
        - name: kdl-server
                env:
                        - name: DRONE_URL
                          value: {{ include "protocol" . }}://drone.{{ .Values.domain }}
```
